### ISSUE TITLE
SPI baudrate hardcoded, should use existing frequency from SPI object

### ISSUE THREAD

**Issue by kattni** [adafruit/Adafruit_CircuitPython_TLC5947#22]
This is the same issue as https://github.com/adafruit/Adafruit_CircuitPython_TLC59711/issues/8. 

Problematic code is here: https://github.com/adafruit/Adafruit_CircuitPython_TLC5947/blob/60d36538ccb9591e5aeaa8c733c184119bb61448/adafruit_tlc5947.py#L161

@FoamyGuy Are you up for fixing this like you did the other TLC lib?

**Comment by FoamyGuy** [comment]
Yep I can handle it in this library as well.

**Comment by tannewt** [comment]
I think it'd be better to remove the configure all-together if we are assuming the SPI is set up appropriately outside of the driver.
