### ISSUE TITLE
Add support for multiple chained TLC's

### ISSUE THREAD

**Issue by ladyada** [adafruit/Adafruit_CircuitPython_TLC5947#6]
https://forums.adafruit.com/viewtopic.php?f=60&t=140130

**Comment by ladyada** [comment]
now with some example code
https://forums.adafruit.com/viewtopic.php?f=60&t=140130&p=709433#p709428

**Comment by caternuson** [comment]
@ladyada looks like they want someone else to make the PR. want me to cobble that together?

**Comment by ladyada** [comment]
yep - i figure the code is good, just needs a merge - no rush on it :)

**Comment by caternuson** [comment]
OK - i've assigned myself for tracking. Got here from the forum thread. @brennen you're tagged also, don't wait for me if you're setup and want to go for it.

**Comment by brennen** [comment]
@caternuson feel free to go for it - i lost track of this one and probably won't get to it yet this week.

**Comment by caternuson** [comment]
OK. I'll need to order up the HW, so I'm week-ish out also for any testing.

I'll do this PR though, if the forum poster doesn't.

**Comment by caternuson** [comment]
I think this can be closed? Because #8

**Comment by brennen** [comment]
Yep, all good.
