### ISSUE TITLE
Update driver to use spi_device.

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_CircuitPython_TLC5947#9]
Driver currently is locking/unlocking the SPI bus directly. Should be updated to do that via `spi_device` and context manager.

**Comment by ladyada** [comment]
i dont think it will work it doesnt use a CS pin, so it isnt an spi_device. the way it does it now is how you handle non-CS SPI devices!

**Comment by caternuson** [comment]
Ah. I see. Thanks.

**Comment by ladyada** [comment]
np - it's a good idea, just a weird chip :D
